name: Bug Report
description: Report a bug or issue with the SinricPro Pico SDK
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: Which SinricPro device type is affected?
      options:
        - Switch
        - DimSwitch
        - Light
        - Motion Sensor
        - Temperature Sensor
        - Contact Sensor
        - Core SDK (not device specific)
        - Other
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      description: Which Pico board are you using?
      options:
        - Raspberry Pi Pico W
        - Raspberry Pi Pico 2 W
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SinricPro SDK Version
      description: Which version or commit are you using?
      placeholder: "e.g., v1.0.0 or commit hash"
    validations:
      required: true

  - type: input
    id: pico-sdk-version
    attributes:
      label: Pico SDK Version
      description: Which pico-sdk version?
      placeholder: "e.g., 2.2.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Tell us what you're experiencing
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure device with '...'
        2. Send command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Serial Output / Logs
      description: Please paste any relevant serial output or logs
      render: shell
      placeholder: Paste logs here

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: c
      placeholder: |
        #include "sinricpro/sinricpro.h"
        // Your code here

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues for duplicates
          required: true
        - label: I have tested with the latest version
          required: false
        - label: I can reproduce this consistently
          required: false
